In [23]:
#import commands
import pandas as pd
import numpy as np
from pathlib import Path

In [24]:
#import csv files
Data_csv = Path("Merged Data/data.csv")
DMV_Fuel_Data = Path("Merged Data/DMV_Fuel_Data.csv")

In [26]:
# Read Data File and store into Pandas DataFrames
Dawson_data = pd.read_csv(Data_csv)
Daniel_data = pd.read_csv(DMV_Fuel_Data)

In [27]:
# print Dawson Data
Dawson_data.head()

,ID,Station Name,Access,Owner,Last_Used,Open_Date,DC_Fast,Level1_Charging,Level2_Charging,Address,City,State,Zipcode,Latitude,Longitude,Pricing,Connection_Type
0,36363,ARUNDEL MILLS ELEMENT HOTELS,public,ChargePoint Network,2024-10-10,2010-07-15,NaN,1.0,NaN,7522 Teague Rd,Hanover,MD,21076,39.155907,-76.717216,NaN,NEMA515
1,39514,Hotel Floyd,public,Non-Networked,2022-11-10,2011-06-01,NaN,NaN,1.0,120 Wilson St,Floyd,VA,24091,36.910575,-80.317360,Free for guests; $10 for non-guests,J1772
2,39763,Passport Nissan - Alexandria,public,Non-Networked,2024-02-12,2011-03-15,1.0,NaN,3.0,150 S Pickett St,Alexandria,VA,22304,38.809670,-77.122190,Free,CHADEMO
3,39764,Priority Nissan - Chantilly,public,Non-Networked,2024-02-12,2011-03-15,1.0,NaN,2.0,14840 Stonecroft Center Ct,Chantilly,VA,20151,38.899800,-77.460330,Free,CHADEMO
4,39765,Colonial Nissan,public,Non-Networked,2024-02-12,2011-03-15,1.0,NaN,2.0,200 Myers Dr,Charlottesville,VA,22901,38.084926,-78.473415,Free,CHADEMO

In [28]:
# Select fields
Fields = Dawson_data[['ID','Station Name','Access','Owner','Last_Used', 'Open_Date','Address', 'City','State','Zipcode','Latitude','Longitude','Pricing', 'Connection_Type' ]]
Fields.head()

,ID,Station Name,Access,Owner,Last_Used,Open_Date,Address,City,State,Zipcode,Latitude,Longitude,Pricing,Connection_Type
0,36363,ARUNDEL MILLS ELEMENT HOTELS,public,ChargePoint Network,2024-10-10,2010-07-15,7522 Teague Rd,Hanover,MD,21076,39.155907,-76.717216,NaN,NEMA515
1,39514,Hotel Floyd,public,Non-Networked,2022-11-10,2011-06-01,120 Wilson St,Floyd,VA,24091,36.910575,-80.317360,Free for guests; $10 for non-guests,J1772
2,39763,Passport Nissan - Alexandria,public,Non-Networked,2024-02-12,2011-03-15,150 S Pickett St,Alexandria,VA,22304,38.809670,-77.122190,Free,CHADEMO
3,39764,Priority Nissan - Chantilly,public,Non-Networked,2024-02-12,2011-03-15,14840 Stonecroft Center Ct,Chantilly,VA,20151,38.899800,-77.460330,Free,CHADEMO
4,39765,Colonial Nissan,public,Non-Networked,2024-02-12,2011-03-15,200 Myers Dr,Charlottesville,VA,22901,38.084926,-78.473415,Free,CHADEMO

In [29]:
# Daniels Data
Daniel_data.head()

,Fuel Type Code,Station Name,Street Address,Date Last Confirmed,Groups With Access Code,State,City,Open Date,ZIP,EV Connector Types,EV Pricing,Latitude,Longitude,Access Code,Facility Type,EV Level1 EVSE Num,EV Level2 EVSE Num,EV DC Fast Count
0,ELEC,One Parking,555 12th St NW,2023-08-10,Public,DC,Washington,2012-03-01,20004,J1772,Free,38.896703,-77.027621,public,PAY_GARAGE,NaN,13.0,NaN
1,ELEC,Florida Power & Light - Washington DC Office,801 Pennsylvania Ave NW,2024-01-09,Private,DC,Washington,2012-01-01,20004,J1772,NaN,38.894354,-77.023723,private,UTILITY,NaN,1.0,NaN
2,ELEC,Maritime Plaza,1201 M St SE,2023-08-10,Private,DC,Washington,2012-12-01,20003,J1772,$0.20 per kWh,38.875930,-76.989468,private,OFFICE_BLDG,NaN,2.0,NaN
3,ELEC,WASH HARBOUR STATION 1,3000 K St NW,2024-10-08,Public,DC,Washington,2011-12-15,20007,J1772,NaN,38.901780,-77.059732,public,NaN,NaN,2.0,NaN
4,ELEC,TOWER COMPANIES 1828 L ST NW #1,1828 L St NW,2024-10-08,Public,DC,Washington,2014-12-09,20036,J1772,NaN,38.903466,-77.042898,public,NaN,NaN,2.0,NaN

In [30]:
# fields
Fields_2 = Daniel_data[['Fuel Type Code','Station Name', 'Street Address','Date Last Confirmed','Groups With Access Code', 'State', 'City', 'Open Date', 'ZIP', 'EV Connector Types', 'EV Pricing', 'Latitude', 'Longitude','Access Code', 'Facility Type', 'EV Level1 EVSE Num',	'EV Level2 EVSE Num', 'EV DC Fast Count'
]]
Fields_2.head()

,Fuel Type Code,Station Name,Street Address,Date Last Confirmed,Groups With Access Code,State,City,Open Date,ZIP,EV Connector Types,EV Pricing,Latitude,Longitude,Access Code,Facility Type,EV Level1 EVSE Num,EV Level2 EVSE Num,EV DC Fast Count
0,ELEC,One Parking,555 12th St NW,2023-08-10,Public,DC,Washington,2012-03-01,20004,J1772,Free,38.896703,-77.027621,public,PAY_GARAGE,NaN,13.0,NaN
1,ELEC,Florida Power & Light - Washington DC Office,801 Pennsylvania Ave NW,2024-01-09,Private,DC,Washington,2012-01-01,20004,J1772,NaN,38.894354,-77.023723,private,UTILITY,NaN,1.0,NaN
2,ELEC,Maritime Plaza,1201 M St SE,2023-08-10,Private,DC,Washington,2012-12-01,20003,J1772,$0.20 per kWh,38.875930,-76.989468,private,OFFICE_BLDG,NaN,2.0,NaN
3,ELEC,WASH HARBOUR STATION 1,3000 K St NW,2024-10-08,Public,DC,Washington,2011-12-15,20007,J1772,NaN,38.901780,-77.059732,public,NaN,NaN,2.0,NaN
4,ELEC,TOWER COMPANIES 1828 L ST NW #1,1828 L St NW,2024-10-08,Public,DC,Washington,2014-12-09,20036,J1772,NaN,38.903466,-77.042898,public,NaN,NaN,2.0,NaN

In [34]:
# Rename columns
Fields_2.rename(columns={
    'Street Address': 'Address',
    'Open Date': 'Open_Date',
    'Date Last Confirmed': 'Last_Used',
    'ZIP': 'Zipcode',
    'EV Connector Types': 'Connection_Type',
    'EV Pricing': 'Pricing',  
    'Access Code': 'Access',  
    'Facility Type': 'Owner',
    'EV Level1 EVSE Num': 'Level1_Charging',
    'EV Level2 EVSE Num': 'Level2_Charging', 
    'EV DC Fast Count': 'DC_Fast'
}, inplace=True)
Fields_2.head()

,Fuel Type Code,Station Name,Address,Last_Used,Groups With Access Code,State,City,Open_Date,Zipcode,Connection_Type,Pricing,Latitude,Longitude,Access,Owner,Level1_Charging,Level2_Charging,DC_Fast
0,ELEC,One Parking,555 12th St NW,2023-08-10,Public,DC,Washington,2012-03-01,20004,J1772,Free,38.896703,-77.027621,public,PAY_GARAGE,NaN,13.0,NaN
1,ELEC,Florida Power & Light - Washington DC Office,801 Pennsylvania Ave NW,2024-01-09,Private,DC,Washington,2012-01-01,20004,J1772,NaN,38.894354,-77.023723,private,UTILITY,NaN,1.0,NaN
2,ELEC,Maritime Plaza,1201 M St SE,2023-08-10,Private,DC,Washington,2012-12-01,20003,J1772,$0.20 per kWh,38.875930,-76.989468,private,OFFICE_BLDG,NaN,2.0,NaN
3,ELEC,WASH HARBOUR STATION 1,3000 K St NW,2024-10-08,Public,DC,Washington,2011-12-15,20007,J1772,NaN,38.901780,-77.059732,public,NaN,NaN,2.0,NaN
4,ELEC,TOWER COMPANIES 1828 L ST NW #1,1828 L St NW,2024-10-08,Public,DC,Washington,2014-12-09,20036,J1772,NaN,38.903466,-77.042898,public,NaN,NaN,2.0,NaN

In [38]:
Daniel_data.rename(columns={
    'Street Address': 'Address',
    'Open Date': 'Open_Date',
    'Date Last Confirmed': 'Last_Used',
    'ZIP': 'Zipcode',
    'EV Connector Types': 'Connection_Type',
    'EV Pricing': 'Pricing',  
    'Access Code': 'Access',  
    'Facility Type': 'Owner',
    'EV Level1 EVSE Num': 'Level1_Charging',
    'EV Level2 EVSE Num': 'Level2_Charging', 
    'EV DC Fast Count': 'DC_Fast'
}, inplace=True)
Daniel_data.head()

,Fuel Type Code,Station Name,Address,Last_Used,Groups With Access Code,State,City,Open_Date,Zipcode,Connection_Type,Pricing,Latitude,Longitude,Access,Owner,Level1_Charging,Level2_Charging,DC_Fast
0,ELEC,One Parking,555 12th St NW,2023-08-10,Public,DC,Washington,2012-03-01,20004,J1772,Free,38.896703,-77.027621,public,PAY_GARAGE,NaN,13.0,NaN
1,ELEC,Florida Power & Light - Washington DC Office,801 Pennsylvania Ave NW,2024-01-09,Private,DC,Washington,2012-01-01,20004,J1772,NaN,38.894354,-77.023723,private,UTILITY,NaN,1.0,NaN
2,ELEC,Maritime Plaza,1201 M St SE,2023-08-10,Private,DC,Washington,2012-12-01,20003,J1772,$0.20 per kWh,38.875930,-76.989468,private,OFFICE_BLDG,NaN,2.0,NaN
3,ELEC,WASH HARBOUR STATION 1,3000 K St NW,2024-10-08,Public,DC,Washington,2011-12-15,20007,J1772,NaN,38.901780,-77.059732,public,NaN,NaN,2.0,NaN
4,ELEC,TOWER COMPANIES 1828 L ST NW #1,1828 L St NW,2024-10-08,Public,DC,Washington,2014-12-09,20036,J1772,NaN,38.903466,-77.042898,public,NaN,NaN,2.0,NaN

In [52]:
# data type for both data sets
Dawson_data.dtypes
Daniel_data.dtypes

Fuel Type Code              object
Station Name                object
Address                     object
Last_Used                   object
Groups With Access Code     object
State                       object
City                        object
Open_Date                   object
Zipcode                      int64
Connection_Type             object
Pricing                     object
Latitude                   float64
Longitude                  float64
Access                      object
Owner                       object
Level1_Charging            float64
Level2_Charging            float64
DC_Fast                    float64
ID                          object
dtype: object

In [55]:
# fix the different data set types for ID
Dawson_data['ID'] = Dawson_data['ID'].astype(str)
Daniel_data['ID'] = Daniel_data['ID'].astype(str)

In [59]:
#merge data frames
merge_columns = [
    'ID', 'Station Name', 'Access', 'Owner', 'Last_Used', 'Open_Date',
    'DC_Fast', 'Level1_Charging', 'Level2_Charging', 'Address', 'City',
    'State', 'Zipcode', 'Latitude', 'Longitude', 'Pricing',
    'Connection_Type'
]

if 'Owner' not in Daniel_data.columns:
    Daniel_data['Owner'] = None 

DMV_Merge = pd.merge(Dawson_data, Daniel_data, on=merge_columns, how='outer')
DMV_Merge.head()

,ID,Station Name,Access,Owner,Last_Used,Open_Date,DC_Fast,Level1_Charging,Level2_Charging,Address,City,State,Zipcode,Latitude,Longitude,Pricing,Connection_Type,Fuel Type Code,Groups With Access Code
0,100283,ECHELON AT ODEN NOVUS ODENTON,public,ChargePoint Network,2024-10-10,2018-08-09,NaN,NaN,2.0,313 Nevada Ave,Odenton,MD,21113,39.092476,-76.709341,NaN,J1772,NaN,NaN
1,100325,Laureate Education Inc,public,Non-Networked,2022-11-10,2018-08-08,NaN,NaN,4.0,7065 Samuel Morse Dr,Columbia,MD,21046,39.168759,-76.811733,Free,J1772,NaN,NaN
2,100326,Mercy Medical Center - Bunting Garage,public,Non-Networked,2022-11-10,2018-08-08,NaN,NaN,4.0,301 Saint Paul Pl,Baltimore,MD,21202,39.292550,-76.613550,Free,J1772,NaN,NaN
3,100466,GARAGE C #1 GARAGE A LVL 1C,public,ChargePoint Network,2024-10-10,2018-08-22,NaN,NaN,2.0,5 Airport Parking Dep Rd,Norfolk,VA,23518,36.899599,-76.206422,NaN,J1772,NaN,NaN
4,100468,GARAGE C #1 GARAGE A LVL 1B,public,ChargePoint Network,2024-10-10,2018-08-22,NaN,NaN,2.0,31 Airport Parking Dep Rd,Norfolk,VA,23518,36.899734,-76.206656,NaN,J1772,NaN,NaN

In [60]:
# check for duplicates 
duplicate_count = DMV_Merge.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

In [61]:
# create output path csv file
output_path = Path("DMV_Merge.csv")
DMV_Merge.to_csv(output_path, index=False)